// Static mapping tables
// src/constants/geoMaps.ts

export const CN_ZH_TO_EN: Record<string, string> = {
    "北京": "Beijing",
    "北京市": "Beijing",
    "上海": "Shanghai",
    "上海市": "Shanghai",
    "天津": "Tianjin",
    "天津市": "Tianjin",
    "重庆": "Chongqing",
    "重庆市": "Chongqing",
  
    "浙江": "Zhejiang",
    "浙江省": "Zhejiang",
    "江苏": "Jiangsu",
    "江苏省": "Jiangsu",
    "安徽": "Anhui",
    "安徽省": "Anhui",
    "福建": "Fujian",
    "福建省": "Fujian",
    "江西": "Jiangxi",
    "江西省": "Jiangxi",
    "山东": "Shandong",
    "山东省": "Shandong",
    "河南": "Henan",
    "河南省": "Henan",
    "河北": "Hebei",
    "河北省": "Hebei",
    "湖北": "Hubei",
    "湖北省": "Hubei",
    "湖南": "Hunan",
    "湖南省": "Hunan",
    "广东": "Guangdong",
    "广东省": "Guangdong",
    "海南": "Hainan",
    "海南省": "Hainan",
    "四川": "Sichuan",
    "四川省": "Sichuan",
    "云南": "Yunnan",
    "云南省": "Yunnan",
    "贵州": "Guizhou",
    "贵州省": "Guizhou",
    "甘肃": "Gansu",
    "甘肃省": "Gansu",
    "青海": "Qinghai",
    "青海省": "Qinghai",
    "陕西": "Shaanxi",
    "陕西省": "Shaanxi",
    "山西": "Shanxi",
    "山西省": "Shanxi",
    "辽宁": "Liaoning",
    "辽宁省": "Liaoning",
    "吉林": "Jilin",
    "吉林省": "Jilin",
  
    "广西": "Guangxi",
    "广西壮族自治区": "Guangxi",
    "宁夏": "Ningxia",
    "宁夏回族自治区": "Ningxia",
    "新疆": "Xinjiang",
    "新疆维吾尔自治区": "Xinjiang",
    "西藏": "Tibet",
    "西藏自治区": "Tibet",
    "内蒙古": "Inner Mongolia",
    "内蒙古自治区": "Inner Mongolia",

    "Hong Kong": "香港特别行政区",
    "Macau": "澳门特别行政区",
    "Macao": "澳门特别行政区",
  };
  
  export const US_ABBR_TO_NAME: Record<string, string> = {
    AL: "Alabama",
    AK: "Alaska",
    AZ: "Arizona",
    AR: "Arkansas",
    CA: "California",
    CO: "Colorado",
    CT: "Connecticut",
    DE: "Delaware",
    FL: "Florida",
    GA: "Georgia",
    HI: "Hawaii",
    ID: "Idaho",
    IL: "Illinois",
    IN: "Indiana",
    IA: "Iowa",
    KS: "Kansas",
    KY: "Kentucky",
    LA: "Louisiana",
    ME: "Maine",
    MD: "Maryland",
    MA: "Massachusetts",
    MI: "Michigan",
    MN: "Minnesota",
    MS: "Mississippi",
    MO: "Missouri",
    MT: "Montana",
    NE: "Nebraska",
    NV: "Nevada",
    NH: "New Hampshire",
    NJ: "New Jersey",
    NM: "New Mexico",
    NY: "New York",
    NC: "North Carolina",
    ND: "North Dakota",
    OH: "Ohio",
    OK: "Oklahoma",
    OR: "Oregon",
    PA: "Pennsylvania",
    RI: "Rhode Island",
    SC: "South Carolina",
    SD: "South Dakota",
    TN: "Tennessee",
    TX: "Texas",
    UT: "Utah",
    VT: "Vermont",
    VA: "Virginia",
    WA: "Washington",
    WV: "West Virginia",
    WI: "Wisconsin",
    WY: "Wyoming",
    DC: "District of Columbia"
  };

  export const CN_EN_TO_ZH: Record<string, string> = {
  "Beijing": "北京市",
  "Shanghai": "上海市",
  "Tianjin": "天津市",
  "Chongqing": "重庆市",
  
  "Hebei": "河北省",
  "Shanxi": "山西省",
  "Liaoning": "辽宁省",
  "Jilin": "吉林省",
  "Heilongjiang": "黑龙江省",
  "Jiangsu": "江苏省",
  "Zhejiang": "浙江省",
  "Anhui": "安徽省",
  "Fujian": "福建省",
  "Jiangxi": "江西省",
  "Shandong": "山东省",
  "Henan": "河南省",
  "Hubei": "湖北省",
  "Hunan": "湖南省",
  "Guangdong": "广东省",
  "Hainan": "海南省",
  "Sichuan": "四川省",
  "Guizhou": "贵州省",
  "Yunnan": "云南省",
  "Shaanxi": "陕西省",
  "Gansu": "甘肃省",
  "Qinghai": "青海省",
  "Taiwan": "台湾省",

  "Inner Mongolia": "内蒙古自治区",
  "Guangxi": "广西壮族自治区",
  "Tibet": "西藏自治区",
  "Ningxia": "宁夏回族自治区",
  "Xinjiang": "新疆维吾尔自治区",
  
  "Hong Kong": "香港特别行政区",
  "Macao": "澳门特别行政区"
};

